/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/shahpratikr/k8s-dev-assignments/assignment-1/pkg/apis/shahpratikr.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotBackups implements SnapshotBackupInterface
type FakeSnapshotBackups struct {
	Fake *FakeShahpratikrV1alpha1
	ns   string
}

var snapshotbackupsResource = schema.GroupVersionResource{Group: "shahpratikr.dev", Version: "v1alpha1", Resource: "snapshotbackups"}

var snapshotbackupsKind = schema.GroupVersionKind{Group: "shahpratikr.dev", Version: "v1alpha1", Kind: "SnapshotBackup"}

// Get takes name of the snapshotBackup, and returns the corresponding snapshotBackup object, and an error if there is any.
func (c *FakeSnapshotBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SnapshotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snapshotbackupsResource, c.ns, name), &v1alpha1.SnapshotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotBackup), err
}

// List takes label and field selectors, and returns the list of SnapshotBackups that match those selectors.
func (c *FakeSnapshotBackups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SnapshotBackupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snapshotbackupsResource, snapshotbackupsKind, c.ns, opts), &v1alpha1.SnapshotBackupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SnapshotBackupList{ListMeta: obj.(*v1alpha1.SnapshotBackupList).ListMeta}
	for _, item := range obj.(*v1alpha1.SnapshotBackupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotBackups.
func (c *FakeSnapshotBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snapshotbackupsResource, c.ns, opts))

}

// Create takes the representation of a snapshotBackup and creates it.  Returns the server's representation of the snapshotBackup, and an error, if there is any.
func (c *FakeSnapshotBackups) Create(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.CreateOptions) (result *v1alpha1.SnapshotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snapshotbackupsResource, c.ns, snapshotBackup), &v1alpha1.SnapshotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotBackup), err
}

// Update takes the representation of a snapshotBackup and updates it. Returns the server's representation of the snapshotBackup, and an error, if there is any.
func (c *FakeSnapshotBackups) Update(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.UpdateOptions) (result *v1alpha1.SnapshotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snapshotbackupsResource, c.ns, snapshotBackup), &v1alpha1.SnapshotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotBackup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSnapshotBackups) UpdateStatus(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.UpdateOptions) (*v1alpha1.SnapshotBackup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(snapshotbackupsResource, "status", c.ns, snapshotBackup), &v1alpha1.SnapshotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotBackup), err
}

// Delete takes name of the snapshotBackup and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(snapshotbackupsResource, c.ns, name, opts), &v1alpha1.SnapshotBackup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snapshotbackupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SnapshotBackupList{})
	return err
}

// Patch applies the patch and returns the patched snapshotBackup.
func (c *FakeSnapshotBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SnapshotBackup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotbackupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SnapshotBackup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotBackup), err
}
