/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/shahpratikr/k8s-dev-assignments/assignment-1/pkg/apis/shahpratikr.dev/v1alpha1"
	scheme "github.com/shahpratikr/k8s-dev-assignments/assignment-1/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SnapshotBackupsGetter has a method to return a SnapshotBackupInterface.
// A group's client should implement this interface.
type SnapshotBackupsGetter interface {
	SnapshotBackups(namespace string) SnapshotBackupInterface
}

// SnapshotBackupInterface has methods to work with SnapshotBackup resources.
type SnapshotBackupInterface interface {
	Create(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.CreateOptions) (*v1alpha1.SnapshotBackup, error)
	Update(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.UpdateOptions) (*v1alpha1.SnapshotBackup, error)
	UpdateStatus(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.UpdateOptions) (*v1alpha1.SnapshotBackup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SnapshotBackup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SnapshotBackupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SnapshotBackup, err error)
	SnapshotBackupExpansion
}

// snapshotBackups implements SnapshotBackupInterface
type snapshotBackups struct {
	client rest.Interface
	ns     string
}

// newSnapshotBackups returns a SnapshotBackups
func newSnapshotBackups(c *ShahpratikrV1alpha1Client, namespace string) *snapshotBackups {
	return &snapshotBackups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the snapshotBackup, and returns the corresponding snapshotBackup object, and an error if there is any.
func (c *snapshotBackups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SnapshotBackup, err error) {
	result = &v1alpha1.SnapshotBackup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotbackups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SnapshotBackups that match those selectors.
func (c *snapshotBackups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SnapshotBackupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SnapshotBackupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snapshotbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested snapshotBackups.
func (c *snapshotBackups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("snapshotbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a snapshotBackup and creates it.  Returns the server's representation of the snapshotBackup, and an error, if there is any.
func (c *snapshotBackups) Create(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.CreateOptions) (result *v1alpha1.SnapshotBackup, err error) {
	result = &v1alpha1.SnapshotBackup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("snapshotbackups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(snapshotBackup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a snapshotBackup and updates it. Returns the server's representation of the snapshotBackup, and an error, if there is any.
func (c *snapshotBackups) Update(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.UpdateOptions) (result *v1alpha1.SnapshotBackup, err error) {
	result = &v1alpha1.SnapshotBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snapshotbackups").
		Name(snapshotBackup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(snapshotBackup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *snapshotBackups) UpdateStatus(ctx context.Context, snapshotBackup *v1alpha1.SnapshotBackup, opts v1.UpdateOptions) (result *v1alpha1.SnapshotBackup, err error) {
	result = &v1alpha1.SnapshotBackup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snapshotbackups").
		Name(snapshotBackup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(snapshotBackup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the snapshotBackup and deletes it. Returns an error if one occurs.
func (c *snapshotBackups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotbackups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *snapshotBackups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snapshotbackups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched snapshotBackup.
func (c *snapshotBackups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SnapshotBackup, err error) {
	result = &v1alpha1.SnapshotBackup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("snapshotbackups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
