/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	shahpratikrdevv1alpha1 "github.com/shahpratikr/k8s-dev-assignments/assignment-1/pkg/apis/shahpratikr.dev/v1alpha1"
	versioned "github.com/shahpratikr/k8s-dev-assignments/assignment-1/pkg/client/clientset/versioned"
	internalinterfaces "github.com/shahpratikr/k8s-dev-assignments/assignment-1/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/shahpratikr/k8s-dev-assignments/assignment-1/pkg/client/listers/shahpratikr.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SnapshotBackupInformer provides access to a shared informer and lister for
// SnapshotBackups.
type SnapshotBackupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SnapshotBackupLister
}

type snapshotBackupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSnapshotBackupInformer constructs a new informer for SnapshotBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSnapshotBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSnapshotBackupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSnapshotBackupInformer constructs a new informer for SnapshotBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSnapshotBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShahpratikrV1alpha1().SnapshotBackups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShahpratikrV1alpha1().SnapshotBackups(namespace).Watch(context.TODO(), options)
			},
		},
		&shahpratikrdevv1alpha1.SnapshotBackup{},
		resyncPeriod,
		indexers,
	)
}

func (f *snapshotBackupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSnapshotBackupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *snapshotBackupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&shahpratikrdevv1alpha1.SnapshotBackup{}, f.defaultInformer)
}

func (f *snapshotBackupInformer) Lister() v1alpha1.SnapshotBackupLister {
	return v1alpha1.NewSnapshotBackupLister(f.Informer().GetIndexer())
}
