name: docker-image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: pratikrshah/build

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    #   with:
    #     fetch-depth: 0
    # - uses: tj-actions/changed-files@v35
    #   name: Get changed files
    #   id: changed-files
    #   with:
    #     files: docker/build/Dockerfile
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    #  if: steps.changed-files.outputs.any_changed == 'true'
    - name: Login to Docker Hub
      uses: docker/login-action@v2
    #  if: steps.changed-files.outputs.any_changed == 'true'
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
    #  if: steps.changed-files.outputs.any_changed == 'true'
      with:
        context: "{{defaultContext}}:docker/build"
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ inputs.tag }}
