name: docker-image

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: docker.io
  IMAGE_NAME: pratikrshah/build

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      with:
        filters: |
          docker-build:
            - 'docker/build/**'
    - name: echo docker-build
      run: echo ${{ steps.filter.outputs }}
    - name: workflow tests
      if: steps.filter.outputs.docker-build == 'true'
      run: echo "Workflow file"
    - name: not workflow tests
      if: steps.filter.outputs.docker-build != 'true'
      run: echo "NOT workflow file"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      if: steps.filter.outputs.docker-build == 'true'
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: steps.filter.outputs.docker-build == 'true'
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      if: steps.filter.outputs.docker-build == 'true'
      with:
        context: "{{defaultContext}}:docker/build"
        push: true
        tags: pratikrshah/build:v0.0.23
