name: docker-image

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: docker.io
  IMAGE_NAME: pratikrshah/build

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.docker-build }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      with:
        filters: |
          docker-build:
            - 'docker/build/**'
    - name: workflow tests
      if: steps.filter.outputs.docker-build == 'true'
      run: echo "Workflow file"

    - name: not workflow tests
      if: steps.filter.outputs.docker-build != 'true'
      run: echo "NOT workflow file"

  docker:
    runs-on: ubuntu-latest
    needs: paths-filter
    #if: needs.paths-filter.outputs.output1 == 'true'
    steps:
      - name: echo output1
        run: echo needs.paths-filter.outputs.output1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: "{{defaultContext}}:docker/build"
      #     push: true
      #     tags: pratikrshah/build:v0.0.23
